
  export const colors = ["red", "blue", "yellow", "green", "white", "black", "purple"]
  export const attributes = ["data", "vaccine", "free", "virus", "variable"]
  export const levels = [2, 3, 4, 5, 6, 7]
  export const cardtypes = ["digimon", "digi-egg", "option", "tamer"]
  export const stages = ["armor form", "baby", "champion", "d-reaper", "hybrid", "in-training", "mega", "rookie", "ultimate"]
  export const playCosts = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
  export const evoCosts = [0, 1, 2, 3, 4, 5, 6, 7, 8]
  export const digiTypes = [
    "9000",
    "AA Defense Agent",
    "Abadin Electronics",
    "Ability Synthesis Agent",
    "Abnormal",
    "Alien",
    "Alien Humanoid",
    "Amphibian",
    "Ancient",
    "Ancient Animal",
    "Ancient Aquabeast",
    "Ancient Bird",
    "Ancient Birdkin",
    "Ancient Crustacean",
    "Ancient Dragon",
    "Ancient Dragonkin",
    "Ancient Fairy",
    "Ancient Fish",
    "Ancient Holy Warrior",
    "Ancient Insectoid",
    "Ancient Mineral",
    "Ancient Mutant",
    "Ancient Mythical Beast",
    "Ancient Plant",
    "Android",
    "Angel",
    "Animal",
    "Ankylosaur",
    "Aquabeast",
    "Aquatic",
    "Archangel",
    "Armor",
    "Authority",
    "Avatar",
    "Avian",
    "Baby Dragon",
    "Base Defense Agent",
    "Beast",
    "Beast Dragon",
    "Beast Knight",
    "Beastkin",
    "Bird",
    "Bird Dragon",
    "Birdkin",
    "Blue Flare",
    "Boss",
    "Bulb",
    "Carnivorous Plant",
    "Ceratopsian",
    "Cherub",
    "Commander Agent",
    "Composite",
    "Composition",
    "CRT",
    "Crustacean",
    "Cyborg",
    "D-Brigade",
    "Dark Animal",
    "Dark Dragon",
    "Dark Knight",
    "Demon",
    "Demon Lord",
    "Deva",
    "DigiPolice",
    "Dinosaur",
    "Dominion",
    "Dragon",
    "Dragon Warrior",
    "Dragonkin",
    "Earth Dragon",
    "Enhancement",
    "Espionage Agent",
    "Evil",
    "Evil Dragon",
    "Fairy",
    "Fallen Angel",
    "Fire",
    "Fire Dragon",
    "Flame",
    "Food",
    "Four Great Dragons",
    "Four Sovereigns",
    "Galaxy",
    "General",
    "Ghost",
    "Giant Bird",
    "God Beast",
    "Grappling Agent",
    "Ground Combat Agent",
    "Holy Beast",
    "Holy Bird",
    "Holy Dragon",
    "Holy Sword",
    "Holy Warrior",
    "Hunter",
    "Ice-Snow",
    "Icy",
    "Insectoid",
    "Intel Acquisition Agent",
    "Invader",
    "Larva",
    "LCD",
    "Legend-Arms",
    "Lesser",
    "LIBERATOR",
    "Light Dragon",
    "Light Fang",
    "Machine",
    "Machine Dragon",
    "Magic Knight",
    "Magic Warrior",
    "Major",
    "Mammal",
    "Marine Man",
    "Mine",
    "Mineral",
    "Mini Angel",
    "Mini Bird",
    "Mini Dragon",
    "Minor",
    "Mollusk",
    "Monk",
    "Mothership Agent",
    "Musical Instrument",
    "Mutant",
    "Mysterious Beast",
    "Mysterious Bird",
    "Mythical",
    "Mythical Animal",
    "Mythical Beast",
    "Mythical Dragon",
    "Night Claw",
    "NO DATA",
    "Parasite",
    "Perfect",
    "Pixie",
    "Plesiosaur",
    "Principality",
    "Puppet",
    "Rare Animal",
    "Reconnaissance Agent",
    "Reptile",
    "Reptile Man",
    "Rock",
    "Rock Dragon",
    "Royal Knight",
    "Sea Animal",
    "Sea Beast",
    "Seraph",
    "Seven Great Demon Lords",
    "Shaman",
    "Skeleton",
    "Sky Dragon",
    "SoC",
    "Super Major",
    "Tathāgata",
    "Ten Warriors",
    "Three Great Angels",
    "Throne",
    "Tropical Fish",
    "Twilight",
    "Unanalyzable",
    "Undead",
    "Unidentified",
    "Unique",
    "Unknown",
    "Vegetation",
    "Virtue",
    "Warrior",
    "Weapon",
    "Wizard",
    "X Antibody",
    "Xros Heart",]
